/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mocktree_actions.h"

typedef struct _CMOCK_none_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  unsigned char Expected_pos;

} CMOCK_none_CALL_INSTANCE;

typedef struct _CMOCK_pattFrm_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  unsigned char Expected_pos;

} CMOCK_pattFrm_CALL_INSTANCE;

typedef struct _CMOCK_pattOk_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  unsigned char Expected_pos;

} CMOCK_pattOk_CALL_INSTANCE;

typedef struct _CMOCK_collect_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  unsigned char Expected_c;

} CMOCK_collect_CALL_INSTANCE;

static struct Mocktree_actionsInstance
{
  CMOCK_MEM_INDEX_TYPE none_CallInstance;
  CMOCK_MEM_INDEX_TYPE pattFrm_CallInstance;
  CMOCK_MEM_INDEX_TYPE pattOk_CallInstance;
  CMOCK_MEM_INDEX_TYPE collect_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mocktree_actions_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.none_CallInstance, cmock_line, "Function 'none' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.pattFrm_CallInstance, cmock_line, "Function 'pattFrm' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.pattOk_CallInstance, cmock_line, "Function 'pattOk' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.collect_CallInstance, cmock_line, "Function 'collect' called less times than expected.");
}

void Mocktree_actions_Init(void)
{
  Mocktree_actions_Destroy();
}

void Mocktree_actions_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void none(unsigned char pos)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_none_CALL_INSTANCE* cmock_call_instance = (CMOCK_none_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.none_CallInstance);
  Mock.none_CallInstance = CMock_Guts_MemNext(Mock.none_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'none' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_pos, pos, cmock_line, "Function 'none' called with unexpected value for argument 'pos'.");
  }
}

void CMockExpectParameters_none(CMOCK_none_CALL_INSTANCE* cmock_call_instance, unsigned char pos)
{
  cmock_call_instance->Expected_pos = pos;
}

void none_CMockExpect(UNITY_LINE_TYPE cmock_line, unsigned char pos)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_none_CALL_INSTANCE));
  CMOCK_none_CALL_INSTANCE* cmock_call_instance = (CMOCK_none_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.none_CallInstance = CMock_Guts_MemChain(Mock.none_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_none(cmock_call_instance, pos);
}

void pattFrm(unsigned char pos)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_pattFrm_CALL_INSTANCE* cmock_call_instance = (CMOCK_pattFrm_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.pattFrm_CallInstance);
  Mock.pattFrm_CallInstance = CMock_Guts_MemNext(Mock.pattFrm_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'pattFrm' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_pos, pos, cmock_line, "Function 'pattFrm' called with unexpected value for argument 'pos'.");
  }
}

void CMockExpectParameters_pattFrm(CMOCK_pattFrm_CALL_INSTANCE* cmock_call_instance, unsigned char pos)
{
  cmock_call_instance->Expected_pos = pos;
}

void pattFrm_CMockExpect(UNITY_LINE_TYPE cmock_line, unsigned char pos)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_pattFrm_CALL_INSTANCE));
  CMOCK_pattFrm_CALL_INSTANCE* cmock_call_instance = (CMOCK_pattFrm_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.pattFrm_CallInstance = CMock_Guts_MemChain(Mock.pattFrm_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_pattFrm(cmock_call_instance, pos);
}

void pattOk(unsigned char pos)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_pattOk_CALL_INSTANCE* cmock_call_instance = (CMOCK_pattOk_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.pattOk_CallInstance);
  Mock.pattOk_CallInstance = CMock_Guts_MemNext(Mock.pattOk_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'pattOk' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_pos, pos, cmock_line, "Function 'pattOk' called with unexpected value for argument 'pos'.");
  }
}

void CMockExpectParameters_pattOk(CMOCK_pattOk_CALL_INSTANCE* cmock_call_instance, unsigned char pos)
{
  cmock_call_instance->Expected_pos = pos;
}

void pattOk_CMockExpect(UNITY_LINE_TYPE cmock_line, unsigned char pos)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_pattOk_CALL_INSTANCE));
  CMOCK_pattOk_CALL_INSTANCE* cmock_call_instance = (CMOCK_pattOk_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.pattOk_CallInstance = CMock_Guts_MemChain(Mock.pattOk_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_pattOk(cmock_call_instance, pos);
}

void collect(unsigned char c)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_collect_CALL_INSTANCE* cmock_call_instance = (CMOCK_collect_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.collect_CallInstance);
  Mock.collect_CallInstance = CMock_Guts_MemNext(Mock.collect_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'collect' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_c, c, cmock_line, "Function 'collect' called with unexpected value for argument 'c'.");
  }
}

void CMockExpectParameters_collect(CMOCK_collect_CALL_INSTANCE* cmock_call_instance, unsigned char c)
{
  cmock_call_instance->Expected_c = c;
}

void collect_CMockExpect(UNITY_LINE_TYPE cmock_line, unsigned char c)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_collect_CALL_INSTANCE));
  CMOCK_collect_CALL_INSTANCE* cmock_call_instance = (CMOCK_collect_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.collect_CallInstance = CMock_Guts_MemChain(Mock.collect_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_collect(cmock_call_instance, c);
}

